 PILHA SEGMENT PARA STACK 'STACK'
	DB 1024 DUP('PILHA')
PILHA ENDS

DADOS SEGMENT PARA 'DATA'
	MULT1 DW 204Ah
	MULT2 DW 382Ah
	PRODUTO DW 2 DUP(0)
DADOS ENDS

CODIGO SEGMENT PARA 'CODE'
	ASSUME CS:CODIGO, DS:DADOS, SS:PILHA
INICIO:
	MOV AX, DADOS
	MOV DS, AX

	MOV AX, MULT1
	MUL MULT2
	MOV PRODUTO, AX
	MOV PRODUTO+2, DX

	MOV AL, 00H
	MOV AH, 4CH
	INT 21H
CODIGO ENDS

END INICIO
